### ISSUE TITLE
webdev could not run for this project.

### ISSUE THREAD

**Issue by ifgyong** [dart-lang/webdev#1094]
```
Can't load Kernel binary: Invalid kernel binary format version.
webdev could not run for this project.
Dart 2.7.1 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

```

when i run `flutter pub get `

```
Running "flutter pub get" in myapp_test_web...                      0.6s

 flutter channel

  master
  dev
* beta
  stable



flutter --version

Flutter 1.21.0-9.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 81a45ec2e5 (6 days ago) • 2020-08-27 14:14:33 -0700
Engine • revision 20a9531835
Tools • Dart 2.10.0 (build 2.10.0-7.3.beta)

```

this is an error.

**Comment by ifgyong** [comment]
it must be copy dir `packages` from   simples of [flutter_web] (https://github.com/flutter/flutter_web),and then 
- `flutter pub global activate webdev`
add 

```
dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
flutter:
  uses-material-design: true
dependency_overrides:
  flutter_web:
    path: ./packages/flutter_web
  flutter_web_ui:
    path: ./packages/flutter_web_ui
```

to yaml

- ` flutter pub get `

it is done
