### ISSUE TITLE
Create vm service models

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#121]
It looks like this is going to require a custom builder, probably partying on a yaml file.

Going through the types I am thinking a format like the following:

## Config

key | value | default
--- | --- | --
classes | Map<String, [Class](#class)> |
enums | Map<String, List\<String\>> |

## Class

key | value | default
--- | --- | --
extends | String |
fields | Map<String, [Field](#field)> |

## Field

key | value | default
--- | --- | --
type | String | 
optional | boolean | false

cc @natebosch @grouma @vsmenon

**Comment by jakemac53** [comment]
Example yaml file for all the models up to and including the `Event` type:

```yaml
classes:
  BoundField:
    fields:
      decl:
        type: '@Field'
      value:
        type: '@Instance|Sentinel'
  BoundVariable:
    fields:
      name:
        type: string
      value:
        type: '@Instance|@TypeArguments|Sentinel'
      declarationTokenPos:
        type: int
      scopeStartTokenPos:
        type: int
      scopeEndTokenPos:
        type: int
  Breakpoint:
    extends: Object
    fields:
      breakpointNumber:
        type: int
      resolved:
        type: bool
      isSyntheticAsyncContinuation:
        type: bool
        optional: true
      location:
        type: SourceLocation|UnresolvedSourceLocation
  '@Class':
    extends: '@Object'
    fields:
      name:
        type: string
  Class:
    extends: Object
    fields:
      name:
        type: string
      error:
        type: '@Error'
        optional: true
      abstract:
        type: bool
      const:
        type: bool
      library:
        type: '@Library'
      location:
        type: SourceLocation
        optional: true
      super:
        type: '@Class'
        optional: true
      superType:
        type: '@Instance'
        optional: true
      interfaces:
        type: '@Instance[]'
      mixin:
        type: '@Instance'
        optional: true
      fields:
        type: '@Field[]'
      functions:
        type: '@Function[]'
      subclasses:
        type: '@Class[]'
  ClassList:
    extends: Response
    fields:
      classes: '@Class[]'
  '@Code':
    extends: '@Object'
    fields:
      name:
        type: string
      kind:
        type: CodeKind
  Code:
    extends: '@Object'
    fields:
      name:
        type: string
      kind:
        type: CodeKind
  '@Context':
    extends: '@Object'
    fields:
      length:
        type: int
  Context:
    extends: Object
    fields:
      length:
        type: int
      parent:
        type: Context
        optional: true
      variables:
        type: 'ContextElement[]'
  ContextElement:
    fields:
      value:
        type: '@Instance|Sentinel'
  '@Error':
    extends: '@Object'
    fields:
      kind:
        type: ErrorKind
      message:
        type: string
  Error:
    extends: Object
    fields:
      kind:
        type: ErrorKind
      message:
        type: string
      exception:
        type: '@Instance'
        optional: true
      stacktrace:
        type: '@Instance'
        optional: true
  Event:
    extends: Response
    fields:
      kind:
        type: EventKind
      isolate:
        type: '@Isolate'
        optional: true
      vm:
        type: '@VM'
        optional: true
      timestamp:
        type: int
      breakpoint:
        type: Breakpoint
        optional: true
      pauseBreakpoints:
        type: Breakpoint[]
        optional: true
      topFrame:
        type: Frame
        optional: true
      exception:
        type: '@Instance'
        optional: true
      bytes:
        type: string
        optional: true
      inspectee:
        type: '@Instance'
        optional: true
      extensionRPC:
        type: string
        optional: true
      extensionKind:
        type: string
        optional: true
      extensionData:
        type: ExtensionData
        optional: true
      timelineEvents:
        type: TimelineEvent[]
        optional: true
      atAsyncSuspension:
        type: bool
        optional: true
      status:
        type: String
        optional: true

enums:
  CodeKind:
    - Dart
    - Native
    - Stub
    - Tag
    - Collected
  ErrorKind:
    - UnhandledException
    - LanguageError
    - InternalError
    - TerminationError
```
