### ISSUE TITLE
webdev serve and build : main.dart.js not found (404)

### ISSUE THREAD

**Issue by mrtdeh** [dart-lang/webdev#1348]
Hello 

Hi, I run with the following command  in my  root directory of flutter web app : 

``` webdev serve web:8089 --debug ```

and say `main.dart.js` not found in the browser, show me: 

![aaaaa](https://user-images.githubusercontent.com/7369151/125158184-8c41fe80-e184-11eb-9748-80b50d058391.png)

my pubspec.yaml :

```
name: arsa_shop_admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.1.4
  

dev_dependencies:
  build_runner: ^2.0.6
  build_web_compilers: ^3.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


  uses-material-design: true

  ```

and flutter doctor --verbose :

```
[✓] Flutter (Channel master, 2.4.0-1.0.pre.94, on Ubuntu 20.04.2 LTS
    5.8.0-59-generic, locale en_US.UTF-8)
    • Flutter version 2.4.0-1.0.pre.94 at /home/mrtdeh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba143ae21e (3 days ago), 2021-07-06 22:01:02 -0700
    • Engine revision 60eea42346
    • Dart version 2.14.0 (build 2.14.0-284.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /media/mrtdeh/softwares/android-tools
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /media/mrtdeh/softwares/android-tools
    • ANDROID_SDK_ROOT = /media/mrtdeh/softwares/android-tools
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

```
