### ISSUE TITLE
add command-line option to specify compiler optiosn and/or build.yaml location 

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/webdev#175]
The current (somewhat underdocumented) way of using build.yaml to control
compile options is not flexible enough.
If a build.yaml file is present it seems to affect both release and non-release builds and will
override the compiler being used (ddc vs dart2js).

It would be more straight forward to have the release build always use dart2 js and the debug
build always use ddc and have additional options to specify compiler flags.
Short of that, an option to specify the location of the build.yaml would help as well.

**Comment by grouma** [comment]
We actually support this today through the `build.yaml`. You can specify release and dev options. See https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md

Take a look at `dev_options` and `release_options`.

**Comment by robertmuth** [comment]
So, I finally got to take a look and could not make sense of it.

What would help is an example.  Maybe one can be added to here:
https://github.com/dart-lang/build/blob/master/build_config/README.md

**Comment by jakemac53** [comment]
[This section](https://github.com/dart-lang/build/blob/master/build_config/README.md#configuring-builders-applied-to-your-package) mentions these options, basically anywhere you would put `options`, you can instead put `release_options` or `dev_options`. For example:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        # For all modes
        options:
          ...
        # Dev mode only, overrides `options` where there are overlapping keys
        dev_options:
          ...
        # Release mode only, overrides `options` where there are overlapping keys
        release_options:
          ...
```
