### ISSUE TITLE
Suggest use as a dev_dependency instead of global install

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/webdev#2497]
Why don't we recommend installing webdev as a dev_dependency? ([here](https://pub.dev/packages/webdev#installation)).

Then we could add the constraints 
```yaml
dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
```
And we would not have to manually validate constraints of the current apps pubspec.lock, but rely on the pub solver to do it..

Maybe I'm missing something obvious. But it seemed to work when I tried.
