### ISSUE TITLE
client.js:10109 Unhandled error detected in the injected client.js script.

### ISSUE THREAD

**Issue by insinfo** [dart-lang/webdev#2553]
```cosnsole
client.js:10109 Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

TypeError: null: type 'JSNull' is not a subtype of type 'String'

    at Object.wrapException (http://192.168.66.123:8080/dwds/src/injected/client.js:1249:43)
    at Object._asString (http://192.168.66.123:8080/dwds/src/injected/client.js:2823:15)
    at main__closure7.call$1 (http://192.168.66.123:8080/dwds/src/injected/client.js:26887:54)
    at _EventStreamSubscription_closure.call$1 (http://192.168.66.123:8080/dwds/src/injected/client.js:26250:26)
    at StaticClosure._rootRunUnary (http://192.168.66.123:8080/dwds/src/injected/client.js:4365:16)
    at _CustomZone.runUnary$2$2 (http://192.168.66.123:8080/dwds/src/injected/client.js:14412:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://192.168.66.123:8080/dwds/src/injected/client.js:14359:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://192.168.66.123:8080/dwds/src/injected/client.js:14546:25)
    at _callDartFunctionFast1 (http://192.168.66.123:8080/dwds/src/injected/client.js:7871:25)
    at http://192.168.66.123:8080/dwds/src/injected/client.js:7847:18

:8080/$dwdsSseHandler?sseClientId=InjectedClient-8665e965-a744-479a-a760-05062a75f24e:1 
        
        
       GET http://192.168.66.123:8080/$dwdsSseHandler?sseClientId=InjectedClient-8665e965-a744-479a-a760-05062a75f24e net::E

```

#### pubspec.yaml
```yaml
name: new_sali_frontend
version: 4.0.0
publish_to: none

environment:
  sdk: ^3.2.1

dependencies:
  ngdart: 8.0.0-dev.4
  ngrouter: 4.0.0-dev.3
  ngforms: 5.0.0-dev.3   
  #ngdart:     
    #git:
      #ref: master
      #url: https://github.com/insinfo/angular_8.git
    # path:
    #   ../../angular_8
  
  http: any  
  js: any  
  chartjs2: any  
  #ngsecurity:
   #git:
      #ref: main
      #url: https://github.com/angulardart-community/ngsecurity.git 
      #url: https://github.com/insinfo/ngsecurity.git 
  new_sali_core:
    path: ../core
  dart_excel:
   git:
    url: https://github.com/insinfo/dart_excel.git
    ref: main    #branch name  
        

dev_dependencies:  
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0
  sass_builder: ^2.2.1
  

```
