### ISSUE TITLE
Disable packages folder with webdev build?

### ISSUE THREAD

**Issue by DavidRGriswold** [dart-lang/webdev#312]
Hi! I have tried every documented option in webdev build but can't get it to do what I want. I looked for a place to ask this question, but couldn't find one - please feel free to direct me elsewhere if I'm asking the wrong place.

I have an entirely self-contained web app in my `www` folder. An HTML file, css file, a couple of JS dependencies (bootstrap4), some images, and a main.dart. The main.dart file pulls in the rest of my code from my `lib` directory as suggested. There are no dependencies in my `pubspec.yaml` - only a couple of `dev_dependencies`, including `webdev` itself.

What I want `webdev build` to do in release mode is simply to copy over my `www` folder to build, but run `dart2js` in minify mode to get a `main.dart.js` instead of a `main.dart` WITHOUT creating a `packages` folder. But I always get the `packages` folder. It contains folders like `build_runner` and `build_web_compilers` and so on. If I delete the folder, it doesn't seem to affect anything - my code still runs exactly the same way.

I don't pretend to understand everything about the build system, or even close. But it seems to me that in "release" mode I should be getting the minimal possible working code. So what's going on? Is there something else I need to do?

**Comment by jakemac53** [comment]
Most files should be cleaned up, but not everything. There isn't enough information to delete all files, so only the ones that are deemed safe to delete are removed. You can do post-processing of your own to delete these files if you know it is safe.

You could also create a `FileDeletingBuilder` that operates on `lib/**` and apply it to all packages to make that happen as a part of the build. Below is an example of what that can look like. Note that there is a bit of a weird misdirection with the extra builder since we require post-process-builders to be applied by normal builders (the previous use cases were for deleting outputs of builders primarily, or inputs to them like dart files).

lib/builders.dart:

```dart
import 'dart:async';
import 'package:build/build.dart';

PostProcessBuilder fileDeletingBuilder(BuilderOptions options) =>
    FileDeletingBuilder([''],
        isEnabled: options.config['enabled'] as bool ?? true);

/// PostProcessBuilders have to be applied by regular builders today
Builder noopBuilder(_) => NoopBuilder();

class NoopBuilder implements Builder {
  @override
  Map<String, List<String>> get buildExtensions => {};

  NoopBuilder();

  @override
  FutureOr<void> build(BuildStep buildStep) => throw UnimplementedError();
}
```

build.yaml:

```yaml
builders:
  # PostProcessBuilders have to be applied by a normal builder - this builder 
  # does nothing but apply the deploy_cleanup builder to all packages.
  noop:
    builder_factories:
      - noopBuilder
    import: 'package:_test/builders.dart'
    auto_apply: all_packages
    applies_builders:
      - :deploy_cleanup
    build_extensions: {}
post_process_builders:
  deploy_cleanup:
    builder_factory: fileDeletingBuilder
    import: 'package:_test/builders.dart'
    input_extensions:
      # All files are potential inputs to delete
      - ''
    defaults:
      generate_for:
        # Globs of files to delete
        - lib/**
      # Disable in dev mode
      dev_options:
        enabled: false
```
