### ISSUE TITLE
webdev serve uses dart2js instead of dartdevc

### ISSUE THREAD

**Issue by tudor07** [dart-lang/webdev#460]
I run my project using `webdev serve`.
When chaning a file I can see this message:

```
build_web_compilers:entrypoint on web/main.dart: Running dart2js with -O2 --fast-startup --omit-implicit-checks --trust-primitives --packages=.package-81b967ff66eba80eda7583c6a7848036 -oweb/main.dart.js web/main.dart
```

It looks like `dart2js` is used but I though `dardevc` should be used when running `webdev serve`.
Also, reloading is very slow, only one line of code changed or one small thing changed and it takes ~30 seconds to reload.

```
Dart VM version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "macos_x64"
AngularDart 5.3.0
macOS 10.14.4
Chrome Version 74.0.3729.169 
build_runner 1.5.2
build_web_compilers 1.2.2
```

**Comment by jakemac53** [comment]
Yes my assumption is this is a misconfiguration, can you paste your `build.yaml` file if you have one? Or possibly you are running with `-r` (or `--release`)?

**Comment by tudor07** [comment]
Hi guys, thanks for checking this.
This is my build.yaml

```
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
          - test/**.browser_test.dart
          - web/main.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - -O2
            - --fast-startup
            - --minify
            - --omit-implicit-checks
            - --trust-primitives

```
