### ISSUE TITLE
Serving from non-standard web directory gives severe error

### ISSUE THREAD

**Issue by IceBlizz6** [dart-lang/webdev#942]
I'm attempting to serve webdev on a directory named "static", instead of web.
This works perfectly well if the directory is named web, but fails when it's named static

> pub get
> pub global run webdev serve static
```
[INFO] Building new asset graph completed, took 741ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Serving `static` on http://127.0.0.1:8080
[SEVERE]build_web_compilers:ddc_modules on static/main.dart: NoSuchMethodError: The getter 'modules' was called on null.
Receiver: null
Tried calling: modules

[SEVERE]build_web_compilers:entrypoint on static/main.dart: AssetNotFoundException: app|static/main.ddc.module

[INFO] Running build completed, took 603ms
[INFO] Caching finalized dependency graph completed, took 103ms
[SEVERE] Failed after 714ms
[INFO] ------------------------------
```
After this it will keep running.

index.html will still work
http://localhost:8080/
```
Hello world
```

But the endpoint prints out error when trying to get the dart.js file
http://localhost:8080/main.dart.js
```
Build failed for app|static/main.dart.js
```

Structure as follows:
* pubspec.yaml
* build.yaml
* static
    - main.dart
    - index.html

pubspec.yaml:
```
name: app
description: A web app that uses Dart
version: 1.0.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  build_runner: 1.8.0
  build_web_compilers: 2.9.0
```

build.yaml
```
targets:
  $default:
    sources:
      - static/**
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - static/**.dart
```

Since this works  on web i suspect that there needs to be some additional tweaks to build.yaml to whitelist static for other components.

**Comment by jakemac53** [comment]
I think you need to add some additional sources to the target. It is a bit magic for sure but try adding `lib/$lib$` to the targets `sources`. This is the file that build_modules pins its builder on (see [here](https://github.com/dart-lang/build/blob/master/build_web_compilers/build.yaml#L54)).

**Comment by IceBlizz6** [comment]
It worked!
For reference the build.yaml now looks like this:

```
targets:
    $default:
        sources:
            - static/**
            - lib/$lib$
        builders:
            build_web_compilers|entrypoint:
                generate_for:
                    - static/**.dart
```

Before closing this issue i would like to ask the developers why this extra configuration is nescessary?

The command line knows name of the folder that will serve the files.
This seems unnescessary. 
Further, i did not find any sources that could give this "magical" solution, so maybe it atleast needs better documentation.
